/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author nguye
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Home() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelNhapHang = new javax.swing.JPanel();
        txtNameVegetableNhapHang = new javax.swing.JTextField();
        lblVegetable = new javax.swing.JLabel();
        lblUnit = new javax.swing.JLabel();
        txtUnitNhapHang = new javax.swing.JTextField();
        txtAmountNhapHang = new javax.swing.JTextField();
        lblAmountNhapHang = new javax.swing.JLabel();
        txtPriceNhapHang = new javax.swing.JTextField();
        lblPriceNhapHang = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAddNhapHang = new javax.swing.JButton();
        btnUpdateNhapHang = new javax.swing.JButton();
        btnDeleteNhapHang = new javax.swing.JButton();
        btnResetNhapHang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhapHang = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        txtSearchNhapHang = new javax.swing.JTextField();
        btnSearchNhapHang = new javax.swing.JButton();
        jPanelKhachHang = new javax.swing.JPanel();
        txtFullNameCustomer = new javax.swing.JTextField();
        lblFullNameCustomer = new javax.swing.JLabel();
        lblPasswordCustomer = new javax.swing.JLabel();
        txtPasswordCustomer = new javax.swing.JTextField();
        txtAddressCustomers = new javax.swing.JTextField();
        lblAddressCustomer = new javax.swing.JLabel();
        txtCityCustomer = new javax.swing.JTextField();
        lblCiTyCustomer = new javax.swing.JLabel();
        btnAddCustomers = new javax.swing.JButton();
        btnUpdateCustomers = new javax.swing.JButton();
        btnDeleteCustomers = new javax.swing.JButton();
        btnResetCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCustomers = new javax.swing.JTable();
        jScrollBar2 = new javax.swing.JScrollBar();
        txtSearchCustomers = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        jPanelHoaDon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lblVegetableIDOrder = new javax.swing.JLabel();
        txtVegetableIDOrder = new javax.swing.JTextField();
        lblVegetableNameOrder = new javax.swing.JLabel();
        txtVegetableNameOrder = new javax.swing.JTextField();
        lblUintOrder = new javax.swing.JLabel();
        txtUnitOrder = new javax.swing.JTextField();
        lblPriceOrder = new javax.swing.JLabel();
        txtPriceOrder = new javax.swing.JTextField();
        lblNoteOrder = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texAreaNoteOrder = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar3 = new javax.swing.JScrollBar();
        btnAddOrder = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblSearchOrder = new javax.swing.JLabel();
        txtSearchOrder = new javax.swing.JTextField();
        jPanelOrderDetais = new javax.swing.JPanel();
        jPanelThongKe = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");

        jTabbedPane.setBackground(new java.awt.Color(204, 204, 163));
        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanelNhapHang.setBackground(new java.awt.Color(204, 204, 255));
        jPanelNhapHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameVegetableNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameVegetableNhapHangActionPerformed(evt);
            }
        });
        jPanelNhapHang.add(txtNameVegetableNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 235, 30));

        lblVegetable.setText("Vegetable Name :");
        jPanelNhapHang.add(lblVegetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 22));

        lblUnit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUnit.setText("Unit :");
        jPanelNhapHang.add(lblUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 88, 22));

        txtUnitNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitNhapHangActionPerformed(evt);
            }
        });
        jPanelNhapHang.add(txtUnitNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 235, 30));

        txtAmountNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountNhapHangActionPerformed(evt);
            }
        });
        jPanelNhapHang.add(txtAmountNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 235, 30));

        lblAmountNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmountNhapHang.setText("Amount :");
        jPanelNhapHang.add(lblAmountNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 88, 22));

        txtPriceNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceNhapHangActionPerformed(evt);
            }
        });
        jPanelNhapHang.add(txtPriceNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 235, 30));

        lblPriceNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPriceNhapHang.setText("Price: ");
        jPanelNhapHang.add(lblPriceNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 88, 22));

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 102, 153));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelNhapHang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 81, 127, 206));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Images ");
        jPanelNhapHang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 293, 82, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\add_image_20px.png")); // NOI18N
        jButton1.setText("Browse Iamges");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelNhapHang.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 322, -1, -1));

        btnAddNhapHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\add_50px.png")); // NOI18N
        jPanelNhapHang.add(btnAddNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 81, -1, 49));

        btnUpdateNhapHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\pencil_drawing_50px.png")); // NOI18N
        jPanelNhapHang.add(btnUpdateNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 165, -1, 47));

        btnDeleteNhapHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\remove_50px.png")); // NOI18N
        jPanelNhapHang.add(btnDeleteNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 50, 50));

        btnResetNhapHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\reset_50px.png")); // NOI18N
        jPanelNhapHang.add(btnResetNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 171, 50, 50));

        jTableNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "VegetableID ", "CatagoryID", "VegetableName", "Unit", "Amount", "Image", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableNhapHang);
        if (jTableNhapHang.getColumnModel().getColumnCount() > 0) {
            jTableNhapHang.getColumnModel().getColumn(6).setHeaderValue("Image");
            jTableNhapHang.getColumnModel().getColumn(7).setHeaderValue("Price");
        }

        jPanelNhapHang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 907, 330));

        jScrollBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelNhapHang.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 20, 300));
        jPanelNhapHang.add(txtSearchNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 312, 180, 30));

        btnSearchNhapHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\search_20px.png")); // NOI18N
        jPanelNhapHang.add(btnSearchNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 312, 50, 30));

        jTabbedPane.addTab("Nhập Hàng", new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\product_40px.png"), jPanelNhapHang); // NOI18N

        jPanelKhachHang.setBackground(new java.awt.Color(204, 204, 255));
        jPanelKhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFullNameCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameCustomerActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(txtFullNameCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 235, 30));

        lblFullNameCustomer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFullNameCustomer.setText("Full Name :");
        jPanelKhachHang.add(lblFullNameCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 22));

        lblPasswordCustomer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPasswordCustomer.setText("Password :");
        jPanelKhachHang.add(lblPasswordCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 88, 22));

        txtPasswordCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordCustomerActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(txtPasswordCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 235, 30));

        txtAddressCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressCustomersActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(txtAddressCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 235, 30));

        lblAddressCustomer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddressCustomer.setText("Address :");
        jPanelKhachHang.add(lblAddressCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 88, 22));

        txtCityCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityCustomerActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(txtCityCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 235, 30));

        lblCiTyCustomer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCiTyCustomer.setText("City : ");
        jPanelKhachHang.add(lblCiTyCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 88, 22));

        btnAddCustomers.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\add_50px.png")); // NOI18N
        jPanelKhachHang.add(btnAddCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 49));

        btnUpdateCustomers.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\pencil_drawing_50px.png")); // NOI18N
        jPanelKhachHang.add(btnUpdateCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, 47));

        btnDeleteCustomers.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\remove_50px.png")); // NOI18N
        jPanelKhachHang.add(btnDeleteCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 50, 50));

        btnResetCustomer.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\reset_50px.png")); // NOI18N
        jPanelKhachHang.add(btnResetCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 50, 50));

        jTableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Customer ID", "Full Name", "Password", "Adrress", "City"
            }
        ));
        jScrollPane2.setViewportView(jTableCustomers);

        jPanelKhachHang.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 907, 330));

        jScrollBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelKhachHang.add(jScrollBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 20, 300));
        jPanelKhachHang.add(txtSearchCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 190, 30));

        btnSearchCustomer.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\search_20px.png")); // NOI18N
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });
        jPanelKhachHang.add(btnSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 40, 30));

        jTabbedPane.addTab("Khách Hàng", new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\administrator_male_40px.png"), jPanelKhachHang); // NOI18N

        jPanelHoaDon.setBackground(new java.awt.Color(204, 204, 255));
        jPanelHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Customer ID :");
        jPanelHoaDon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 59, 77, 34));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelHoaDon.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 59, 183, 34));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Date :");
        jPanelHoaDon.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 127, 62, 29));
        jPanelHoaDon.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 127, 241, 29));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Total :");
        jPanelHoaDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 191, 37, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelHoaDon.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 183, 241, 32));

        lblVegetableIDOrder.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblVegetableIDOrder.setText("Vegetable ID :");
        jPanelHoaDon.add(lblVegetableIDOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 59, 76, 34));
        jPanelHoaDon.add(txtVegetableIDOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 59, 210, 34));

        lblVegetableNameOrder.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblVegetableNameOrder.setText("Vegetable Name :");
        jPanelHoaDon.add(lblVegetableNameOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 124, -1, -1));
        jPanelHoaDon.add(txtVegetableNameOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 115, 136, 35));

        lblUintOrder.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUintOrder.setText("Unit :");
        jPanelHoaDon.add(lblUintOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 176, 86, -1));
        jPanelHoaDon.add(txtUnitOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 169, 73, 30));

        lblPriceOrder.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPriceOrder.setText("Price :");
        jPanelHoaDon.add(lblPriceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 251, 37, -1));
        jPanelHoaDon.add(txtPriceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 244, 241, 30));

        lblNoteOrder.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNoteOrder.setText("Note :");
        jPanelHoaDon.add(lblNoteOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 211, 65, -1));

        texAreaNoteOrder.setColumns(20);
        texAreaNoteOrder.setRows(5);
        jScrollPane3.setViewportView(texAreaNoteOrder);

        jPanelHoaDon.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 211, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "OrderID", "CustomerI D", "Vegetable ID", "Vegetable Name", "Price", "Unit", "Date", "Total", "Note"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanelHoaDon.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 970, 330));
        jPanelHoaDon.add(jScrollBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 20, 310));

        btnAddOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\add_50px.png")); // NOI18N
        btnAddOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelHoaDon.add(btnAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 50, 50));

        btnDeleteOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\remove_50px.png")); // NOI18N
        btnDeleteOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDeleteOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelHoaDon.add(btnDeleteOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 50, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\pencil_drawing_50px.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelHoaDon.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 50, 50));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\reset_50px.png")); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelHoaDon.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 50, 50));

        lblSearchOrder.setBackground(new java.awt.Color(255, 255, 255));
        lblSearchOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\search_20px.png")); // NOI18N
        lblSearchOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelHoaDon.add(lblSearchOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 30, 30));
        jPanelHoaDon.add(txtSearchOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 190, 30));

        jTabbedPane.addTab("Hóa Đơn", new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\purchase_order_40px.png"), jPanelHoaDon); // NOI18N

        jPanelOrderDetais.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanelOrderDetaisLayout = new javax.swing.GroupLayout(jPanelOrderDetais);
        jPanelOrderDetais.setLayout(jPanelOrderDetaisLayout);
        jPanelOrderDetaisLayout.setHorizontalGroup(
            jPanelOrderDetaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );
        jPanelOrderDetaisLayout.setVerticalGroup(
            jPanelOrderDetaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Chi tiết Hóa Đơn", new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\receipt_40px.png"), jPanelOrderDetais); // NOI18N

        jPanelThongKe.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanelThongKeLayout = new javax.swing.GroupLayout(jPanelThongKe);
        jPanelThongKe.setLayout(jPanelThongKeLayout);
        jPanelThongKeLayout.setHorizontalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );
        jPanelThongKeLayout.setVerticalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Thống Kê ", new javax.swing.ImageIcon("C:\\Users\\nguye\\Documents\\NetBeansProjects\\QuanLyBanHang\\src\\main\\java\\images\\analytics_40px.png"), jPanelThongKe); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameVegetableNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameVegetableNhapHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameVegetableNhapHangActionPerformed

    private void txtUnitNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitNhapHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitNhapHangActionPerformed

    private void txtAmountNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountNhapHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountNhapHangActionPerformed

    private void txtPriceNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceNhapHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceNhapHangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void txtCityCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityCustomerActionPerformed

    private void txtAddressCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressCustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressCustomersActionPerformed

    private void txtPasswordCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordCustomerActionPerformed

    private void txtFullNameCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameCustomerActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomers;
    private javax.swing.JButton btnAddNhapHang;
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDeleteCustomers;
    private javax.swing.JButton btnDeleteNhapHang;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnResetCustomer;
    private javax.swing.JButton btnResetNhapHang;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSearchNhapHang;
    private javax.swing.JButton btnUpdateCustomers;
    private javax.swing.JButton btnUpdateNhapHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelHoaDon;
    private javax.swing.JPanel jPanelKhachHang;
    private javax.swing.JPanel jPanelNhapHang;
    private javax.swing.JPanel jPanelOrderDetais;
    private javax.swing.JPanel jPanelThongKe;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCustomers;
    private javax.swing.JTable jTableNhapHang;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAddressCustomer;
    private javax.swing.JLabel lblAmountNhapHang;
    private javax.swing.JLabel lblCiTyCustomer;
    private javax.swing.JLabel lblFullNameCustomer;
    private javax.swing.JLabel lblNoteOrder;
    private javax.swing.JLabel lblPasswordCustomer;
    private javax.swing.JLabel lblPriceNhapHang;
    private javax.swing.JLabel lblPriceOrder;
    private javax.swing.JLabel lblSearchOrder;
    private javax.swing.JLabel lblUintOrder;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblVegetable;
    private javax.swing.JLabel lblVegetableIDOrder;
    private javax.swing.JLabel lblVegetableNameOrder;
    private javax.swing.JTextArea texAreaNoteOrder;
    private javax.swing.JTextField txtAddressCustomers;
    private javax.swing.JTextField txtAmountNhapHang;
    private javax.swing.JTextField txtCityCustomer;
    private javax.swing.JTextField txtFullNameCustomer;
    private javax.swing.JTextField txtNameVegetableNhapHang;
    private javax.swing.JTextField txtPasswordCustomer;
    private javax.swing.JTextField txtPriceNhapHang;
    private javax.swing.JTextField txtPriceOrder;
    private javax.swing.JTextField txtSearchCustomers;
    private javax.swing.JTextField txtSearchNhapHang;
    private javax.swing.JTextField txtSearchOrder;
    private javax.swing.JTextField txtUnitNhapHang;
    private javax.swing.JTextField txtUnitOrder;
    private javax.swing.JTextField txtVegetableIDOrder;
    private javax.swing.JTextField txtVegetableNameOrder;
    // End of variables declaration//GEN-END:variables
}
